[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
nom = { workspace = true }
thiserror.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
